# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base  # Points to the base directory for all resources

namespace: staging  # Specifies the namespace for all resources in this overlay
