# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../UI_Microservice/manifests/prod
  - ../../API_Microservice/manifests/prod
  - ../../DB_Microservice/manifests/manifests/prod

namespace: prod  # Specifies the namespace for all resources in this overlay
